/*!   GeneXus C# 16_0_9-140712 on 6/15/2020 10:14:45.90
*/
gx.evt.autoSkip = false;
gx.define('wwpbaseobjects.secroleww', false, function () {
   this.ServerClass =  "wwpbaseobjects.secroleww" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.anyGridBaseTable = true;
   this.hasEnterEvent = false;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
      this.AV64ManageFiltersExecutionStep=gx.fn.getIntegerValue("vMANAGEFILTERSEXECUTIONSTEP",'.') ;
      this.AV71TFSecRoleName=gx.fn.getControlValue("vTFSECROLENAME") ;
      this.AV72TFSecRoleName_Sel=gx.fn.getControlValue("vTFSECROLENAME_SEL") ;
      this.AV75TFSecRoleDescription=gx.fn.getControlValue("vTFSECROLEDESCRIPTION") ;
      this.AV76TFSecRoleDescription_Sel=gx.fn.getControlValue("vTFSECROLEDESCRIPTION_SEL") ;
      this.AV96Pgmname=gx.fn.getControlValue("vPGMNAME") ;
      this.AV44OrderedBy=gx.fn.getIntegerValue("vORDEREDBY",'.') ;
      this.AV45OrderedDsc=gx.fn.getControlValue("vORDEREDDSC") ;
      this.AV41GridState=gx.fn.getControlValue("vGRIDSTATE") ;
      this.AV64ManageFiltersExecutionStep=gx.fn.getIntegerValue("vMANAGEFILTERSEXECUTIONSTEP",'.') ;
      this.AV71TFSecRoleName=gx.fn.getControlValue("vTFSECROLENAME") ;
      this.AV72TFSecRoleName_Sel=gx.fn.getControlValue("vTFSECROLENAME_SEL") ;
      this.AV75TFSecRoleDescription=gx.fn.getControlValue("vTFSECROLEDESCRIPTION") ;
      this.AV76TFSecRoleDescription_Sel=gx.fn.getControlValue("vTFSECROLEDESCRIPTION_SEL") ;
      this.AV96Pgmname=gx.fn.getControlValue("vPGMNAME") ;
      this.AV44OrderedBy=gx.fn.getIntegerValue("vORDEREDBY",'.') ;
      this.AV45OrderedDsc=gx.fn.getControlValue("vORDEREDDSC") ;
   };
   this.s142_client=function()
   {
      this.DDO_GRIDContainer.SortedStatus =  gx.text.trim( gx.num.str( this.AV44OrderedBy, 4, 0))+":"+(this.AV45OrderedDsc ? "DSC" : "ASC")  ;
   };
   this.s162_client=function()
   {
      this.AV91FilterFullText =  ''  ;
      this.AV71TFSecRoleName =  ''  ;
      this.AV72TFSecRoleName_Sel =  ''  ;
      this.AV75TFSecRoleDescription =  ''  ;
      this.AV76TFSecRoleDescription_Sel =  ''  ;
      this.DDO_GRIDContainer.SelectedValue_set =  ""  ;
      this.DDO_GRIDContainer.FilteredText_set =  ""  ;
   };
   this.e120o2_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEPAGE", false, null, true, true);
   };
   this.e130o2_client=function()
   {
      return this.executeServerEvent("GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", false, null, true, true);
   };
   this.e140o2_client=function()
   {
      return this.executeServerEvent("DDO_GRID.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e110o2_client=function()
   {
      return this.executeServerEvent("DDO_MANAGEFILTERS.ONOPTIONCLICKED", false, null, true, true);
   };
   this.e150o2_client=function()
   {
      return this.executeServerEvent("'DOINSERT'", false, null, false, false);
   };
   this.e160o2_client=function()
   {
      return this.executeServerEvent("'DOEXPORT'", false, null, false, false);
   };
   this.e170o2_client=function()
   {
      return this.executeServerEvent("'DOEXPORTREPORT'", false, null, false, false);
   };
   this.e210o2_client=function()
   {
      return this.executeServerEvent("ENTER", true, arguments[0], false, false);
   };
   this.e220o2_client=function()
   {
      return this.executeServerEvent("CANCEL", true, arguments[0], false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,30,33,34,35,36,38,39,40,41,42,44,45,46,47,48,49,50,51,53,54,55];
   this.GXLastCtrlId =55;
   this.GridContainer = new gx.grid.grid(this, 2,"WbpLvl2",43,"Grid","Grid","GridContainer",this.CmpContext,this.IsMasterPage,"wwpbaseobjects.secroleww",[],false,1,false,true,0,false,false,false,"",0,"px",0,"px","Novo registro",true,false,false,null,null,false,"",false,[1,1,1,1],false,0,true,false);
   var GridContainer = this.GridContainer;
   GridContainer.addSingleLineEdit("Update",44,"vUPDATE","","Modifica","Update","char",0,"px",20,20,"left",null,[],"Update","Update",true,0,false,false,"Attribute",1,"WWIconActionColumn");
   GridContainer.addSingleLineEdit("Delete",45,"vDELETE","","Eliminar","Delete","char",0,"px",20,20,"left",null,[],"Delete","Delete",true,0,false,false,"Attribute",1,"WWIconActionColumn");
   GridContainer.addBitmap("&Uaassociatefunctionalities","vUAASSOCIATEFUNCTIONALITIES",46,0,"px",17,"px",null,"","","ActionBaseColorAttribute","WWActionColumn");
   GridContainer.addSingleLineEdit(10,47,"SECROLEID","Id","","SecRoleId","int",0,"px",4,4,"right",null,[],10,"SecRoleId",false,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   GridContainer.addSingleLineEdit(91,48,"SECROLENAME","Name","","SecRoleName","svchar",0,"px",40,40,"left",null,[],91,"SecRoleName",true,0,false,false,"Attribute",1,"WWColumn");
   GridContainer.addSingleLineEdit(90,49,"SECROLEDESCRIPTION","Description","","SecRoleDescription","svchar",0,"px",120,80,"left",null,[],90,"SecRoleDescription",true,0,false,false,"Attribute",1,"WWColumn hidden-xs");
   this.GridContainer.emptyText = "";
   this.setGrid(GridContainer);
   this.DVPANEL_TABLEHEADERContainer = gx.uc.getNew(this, 9, 0, "BootstrapPanel", "DVPANEL_TABLEHEADERContainer", "Dvpanel_tableheader", "DVPANEL_TABLEHEADER");
   var DVPANEL_TABLEHEADERContainer = this.DVPANEL_TABLEHEADERContainer;
   DVPANEL_TABLEHEADERContainer.setProp("Class", "Class", "", "char");
   DVPANEL_TABLEHEADERContainer.setProp("Enabled", "Enabled", true, "boolean");
   DVPANEL_TABLEHEADERContainer.setProp("Width", "Width", "100%", "str");
   DVPANEL_TABLEHEADERContainer.setProp("Height", "Height", "100", "str");
   DVPANEL_TABLEHEADERContainer.setProp("AutoWidth", "Autowidth", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("AutoHeight", "Autoheight", true, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Cls", "Cls", "PanelCard_GrayTitle", "str");
   DVPANEL_TABLEHEADERContainer.setProp("ShowHeader", "Showheader", true, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Title", "Title", "Opções", "str");
   DVPANEL_TABLEHEADERContainer.setProp("Collapsible", "Collapsible", true, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Collapsed", "Collapsed", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("ShowCollapseIcon", "Showcollapseicon", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("IconPosition", "Iconposition", "Right", "str");
   DVPANEL_TABLEHEADERContainer.setProp("AutoScroll", "Autoscroll", false, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Visible", "Visible", true, "bool");
   DVPANEL_TABLEHEADERContainer.setProp("Gx Control Type", "Gxcontroltype", '', "int");
   DVPANEL_TABLEHEADERContainer.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(DVPANEL_TABLEHEADERContainer);
   this.GRIDPAGINATIONBARContainer = gx.uc.getNew(this, 52, 34, "DVelop_DVPaginationBar", "GRIDPAGINATIONBARContainer", "Gridpaginationbar", "GRIDPAGINATIONBAR");
   var GRIDPAGINATIONBARContainer = this.GRIDPAGINATIONBARContainer;
   GRIDPAGINATIONBARContainer.setProp("Enabled", "Enabled", true, "boolean");
   GRIDPAGINATIONBARContainer.setProp("Class", "Class", "PaginationBar", "str");
   GRIDPAGINATIONBARContainer.setProp("ShowFirst", "Showfirst", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowPrevious", "Showprevious", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowNext", "Shownext", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("ShowLast", "Showlast", false, "bool");
   GRIDPAGINATIONBARContainer.setProp("PagesToShow", "Pagestoshow", 5, "num");
   GRIDPAGINATIONBARContainer.setProp("PagingButtonsPosition", "Pagingbuttonsposition", "Right", "str");
   GRIDPAGINATIONBARContainer.setProp("PagingCaptionPosition", "Pagingcaptionposition", "Left", "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridClass", "Emptygridclass", "PaginationBarEmptyGrid", "str");
   GRIDPAGINATIONBARContainer.setProp("SelectedPage", "Selectedpage", "", "char");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageSelector", "Rowsperpageselector", true, "bool");
   GRIDPAGINATIONBARContainer.setDynProp("RowsPerPageSelectedValue", "Rowsperpageselectedvalue", 10, "num");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageOptions", "Rowsperpageoptions", "5:WWP_Rows5,10:WWP_Rows10,20:WWP_Rows20,50:WWP_Rows50", "str");
   GRIDPAGINATIONBARContainer.setProp("First", "First", "First", "str");
   GRIDPAGINATIONBARContainer.setProp("Previous", "Previous", "WWP_PagingPreviousCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Next", "Next", "WWP_PagingNextCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("Last", "Last", "Last", "str");
   GRIDPAGINATIONBARContainer.setProp("Caption", "Caption", "Página <CURRENT_PAGE> de <TOTAL_PAGES>", "str");
   GRIDPAGINATIONBARContainer.setProp("EmptyGridCaption", "Emptygridcaption", "WWP_PagingEmptyGridCaption", "str");
   GRIDPAGINATIONBARContainer.setProp("RowsPerPageCaption", "Rowsperpagecaption", "WWP_PagingRowsPerPage", "str");
   GRIDPAGINATIONBARContainer.addV2CFunction('AV89GridCurrentPage', "vGRIDCURRENTPAGE", 'SetCurrentPage');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV89GridCurrentPage=UC.GetCurrentPage();gx.fn.setControlValue("vGRIDCURRENTPAGE",UC.ParentObject.AV89GridCurrentPage); });
   GRIDPAGINATIONBARContainer.addV2CFunction('AV90GridPageCount', "vGRIDPAGECOUNT", 'SetPageCount');
   GRIDPAGINATIONBARContainer.addC2VFunction(function(UC) { UC.ParentObject.AV90GridPageCount=UC.GetPageCount();gx.fn.setControlValue("vGRIDPAGECOUNT",UC.ParentObject.AV90GridPageCount); });
   GRIDPAGINATIONBARContainer.setProp("RecordCount", "Recordcount", '', "str");
   GRIDPAGINATIONBARContainer.setProp("Page", "Page", '', "str");
   GRIDPAGINATIONBARContainer.setProp("Visible", "Visible", true, "bool");
   GRIDPAGINATIONBARContainer.setProp("Gx Control Type", "Gxcontroltype", '', "int");
   GRIDPAGINATIONBARContainer.setC2ShowFunction(function(UC) { UC.show(); });
   GRIDPAGINATIONBARContainer.addEventHandler("ChangePage", this.e120o2_client);
   GRIDPAGINATIONBARContainer.addEventHandler("ChangeRowsPerPage", this.e130o2_client);
   this.setUserControl(GRIDPAGINATIONBARContainer);
   this.DDO_GRIDContainer = gx.uc.getNew(this, 56, 34, "DDOGridTitleSettingsM", "DDO_GRIDContainer", "Ddo_grid", "DDO_GRID");
   var DDO_GRIDContainer = this.DDO_GRIDContainer;
   DDO_GRIDContainer.setProp("Class", "Class", "", "char");
   DDO_GRIDContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_GRIDContainer.setProp("IconType", "Icontype", "Image", "str");
   DDO_GRIDContainer.setProp("Icon", "Icon", "", "str");
   DDO_GRIDContainer.setProp("Caption", "Caption", "", "str");
   DDO_GRIDContainer.setProp("Tooltip", "Tooltip", "", "str");
   DDO_GRIDContainer.setProp("Cls", "Cls", "", "str");
   DDO_GRIDContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_GRIDContainer.setDynProp("FilteredText_set", "Filteredtext_set", "", "char");
   DDO_GRIDContainer.setProp("FilteredText_get", "Filteredtext_get", "", "char");
   DDO_GRIDContainer.setProp("FilteredTextTo_set", "Filteredtextto_set", "", "char");
   DDO_GRIDContainer.setProp("FilteredTextTo_get", "Filteredtextto_get", "", "char");
   DDO_GRIDContainer.setDynProp("SelectedValue_set", "Selectedvalue_set", "", "char");
   DDO_GRIDContainer.setProp("SelectedValue_get", "Selectedvalue_get", "", "char");
   DDO_GRIDContainer.setProp("SelectedText_set", "Selectedtext_set", "", "char");
   DDO_GRIDContainer.setProp("SelectedText_get", "Selectedtext_get", "", "char");
   DDO_GRIDContainer.setProp("SelectedColumn", "Selectedcolumn", "", "char");
   DDO_GRIDContainer.setProp("SelectedColumnFixedFilter", "Selectedcolumnfixedfilter", "", "char");
   DDO_GRIDContainer.setProp("GAMOAuthToken", "Gamoauthtoken", "", "char");
   DDO_GRIDContainer.setProp("TitleControlAlign", "Titlecontrolalign", "", "str");
   DDO_GRIDContainer.setProp("Visible", "Visible", "", "str");
   DDO_GRIDContainer.setDynProp("GridInternalName", "Gridinternalname", "", "str");
   DDO_GRIDContainer.setProp("ColumnIds", "Columnids", "4:SecRoleName|5:SecRoleDescription", "str");
   DDO_GRIDContainer.setProp("ColumnsSortValues", "Columnssortvalues", "1|2", "str");
   DDO_GRIDContainer.setProp("IncludeSortASC", "Includesortasc", "T", "str");
   DDO_GRIDContainer.setProp("IncludeSortDSC", "Includesortdsc", "", "str");
   DDO_GRIDContainer.setProp("AllowGroup", "Allowgroup", "", "str");
   DDO_GRIDContainer.setDynProp("SortedStatus", "Sortedstatus", "", "char");
   DDO_GRIDContainer.setProp("IncludeFilter", "Includefilter", "T", "str");
   DDO_GRIDContainer.setProp("FilterType", "Filtertype", "Character|Character", "str");
   DDO_GRIDContainer.setProp("FilterIsRange", "Filterisrange", "", "str");
   DDO_GRIDContainer.setProp("IncludeDataList", "Includedatalist", "T", "str");
   DDO_GRIDContainer.setProp("DataListType", "Datalisttype", "Dynamic|Dynamic", "str");
   DDO_GRIDContainer.setProp("AllowMultipleSelection", "Allowmultipleselection", "", "str");
   DDO_GRIDContainer.setProp("DataListFixedValues", "Datalistfixedvalues", "", "str");
   DDO_GRIDContainer.setProp("DataListProc", "Datalistproc", "WWPBaseObjects.SecRoleWWGetFilterData", "str");
   DDO_GRIDContainer.setProp("DataListProcParametersPrefix", "Datalistprocparametersprefix", "", "str");
   DDO_GRIDContainer.setProp("DataListUpdateMinimumCharacters", "Datalistupdateminimumcharacters", 0, "num");
   DDO_GRIDContainer.setProp("FixedFilters", "Fixedfilters", "", "str");
   DDO_GRIDContainer.setProp("SelectedFixedFilter", "Selectedfixedfilter", "", "char");
   DDO_GRIDContainer.setProp("SortASC", "Sortasc", "", "str");
   DDO_GRIDContainer.setProp("SortDSC", "Sortdsc", "", "str");
   DDO_GRIDContainer.setProp("AllowGroupText", "Allowgrouptext", "", "str");
   DDO_GRIDContainer.setProp("LoadingData", "Loadingdata", "", "str");
   DDO_GRIDContainer.setProp("CleanFilter", "Cleanfilter", "", "str");
   DDO_GRIDContainer.setProp("RangeFilterFrom", "Rangefilterfrom", "", "str");
   DDO_GRIDContainer.setProp("RangeFilterTo", "Rangefilterto", "", "str");
   DDO_GRIDContainer.setProp("NoResultsFound", "Noresultsfound", "", "str");
   DDO_GRIDContainer.setProp("SearchButtonText", "Searchbuttontext", "", "str");
   DDO_GRIDContainer.addV2CFunction('AV78DDO_TitleSettingsIcons', "vDDO_TITLESETTINGSICONS", 'SetDropDownOptionsTitleSettingsIcons');
   DDO_GRIDContainer.addC2VFunction(function(UC) { UC.ParentObject.AV78DDO_TitleSettingsIcons=UC.GetDropDownOptionsTitleSettingsIcons();gx.fn.setControlValue("vDDO_TITLESETTINGSICONS",UC.ParentObject.AV78DDO_TitleSettingsIcons); });
   DDO_GRIDContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_GRIDContainer.addEventHandler("OnOptionClicked", this.e140o2_client);
   this.setUserControl(DDO_GRIDContainer);
   this.INNEWWINDOW1Container = gx.uc.getNew(this, 57, 34, "InNewWindow", "INNEWWINDOW1Container", "Innewwindow1", "INNEWWINDOW1");
   var INNEWWINDOW1Container = this.INNEWWINDOW1Container;
   INNEWWINDOW1Container.setProp("Class", "Class", "", "char");
   INNEWWINDOW1Container.setProp("Enabled", "Enabled", true, "boolean");
   INNEWWINDOW1Container.setDynProp("Width", "Width", "50", "str");
   INNEWWINDOW1Container.setDynProp("Height", "Height", "50", "str");
   INNEWWINDOW1Container.setProp("Name", "Name", "", "str");
   INNEWWINDOW1Container.setDynProp("Target", "Target", "", "str");
   INNEWWINDOW1Container.setProp("Fullscreen", "Fullscreen", false, "bool");
   INNEWWINDOW1Container.setProp("Location", "Location", true, "bool");
   INNEWWINDOW1Container.setProp("MenuBar", "Menubar", true, "bool");
   INNEWWINDOW1Container.setProp("Resizable", "Resizable", true, "bool");
   INNEWWINDOW1Container.setProp("Scrollbars", "Scrollbars", true, "bool");
   INNEWWINDOW1Container.setProp("TitleBar", "Titlebar", true, "bool");
   INNEWWINDOW1Container.setProp("ToolBar", "Toolbar", true, "bool");
   INNEWWINDOW1Container.setProp("directories", "Directories", true, "bool");
   INNEWWINDOW1Container.setProp("status", "Status", true, "bool");
   INNEWWINDOW1Container.setProp("copyhistory", "Copyhistory", true, "bool");
   INNEWWINDOW1Container.setProp("top", "Top", "5", "str");
   INNEWWINDOW1Container.setProp("left", "Left", "5", "str");
   INNEWWINDOW1Container.setProp("fitscreen", "Fitscreen", false, "bool");
   INNEWWINDOW1Container.setProp("RefreshParentOnClose", "Refreshparentonclose", false, "bool");
   INNEWWINDOW1Container.setProp("Targets", "Targets", '', "str");
   INNEWWINDOW1Container.setProp("Visible", "Visible", true, "bool");
   INNEWWINDOW1Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(INNEWWINDOW1Container);
   this.DDO_MANAGEFILTERSContainer = gx.uc.getNew(this, 28, 0, "BootstrapDropDownOptions", "DDO_MANAGEFILTERSContainer", "Ddo_managefilters", "DDO_MANAGEFILTERS");
   var DDO_MANAGEFILTERSContainer = this.DDO_MANAGEFILTERSContainer;
   DDO_MANAGEFILTERSContainer.setProp("Class", "Class", "", "char");
   DDO_MANAGEFILTERSContainer.setProp("Enabled", "Enabled", true, "boolean");
   DDO_MANAGEFILTERSContainer.setProp("IconType", "Icontype", "FontIcon", "str");
   DDO_MANAGEFILTERSContainer.setProp("Icon", "Icon", "fas fa-filter", "str");
   DDO_MANAGEFILTERSContainer.setProp("Caption", "Caption", "", "str");
   DDO_MANAGEFILTERSContainer.setProp("Tooltip", "Tooltip", "WWP_ManageFiltersTooltip", "str");
   DDO_MANAGEFILTERSContainer.setProp("Cls", "Cls", "ManageFilters", "str");
   DDO_MANAGEFILTERSContainer.setProp("ActiveEventKey", "Activeeventkey", "", "char");
   DDO_MANAGEFILTERSContainer.setProp("TitleControlAlign", "Titlecontrolalign", "Automatic", "str");
   DDO_MANAGEFILTERSContainer.setProp("DropDownOptionsType", "Dropdownoptionstype", "Regular", "str");
   DDO_MANAGEFILTERSContainer.setProp("Visible", "Visible", true, "bool");
   DDO_MANAGEFILTERSContainer.setProp("TitleControlIdToReplace", "Titlecontrolidtoreplace", "", "str");
   DDO_MANAGEFILTERSContainer.addV2CFunction('AV68ManageFiltersData', "vMANAGEFILTERSDATA", 'SetDropDownOptionsData');
   DDO_MANAGEFILTERSContainer.addC2VFunction(function(UC) { UC.ParentObject.AV68ManageFiltersData=UC.GetDropDownOptionsData();gx.fn.setControlValue("vMANAGEFILTERSDATA",UC.ParentObject.AV68ManageFiltersData); });
   DDO_MANAGEFILTERSContainer.setProp("Gx Control Type", "Gxcontroltype", '', "int");
   DDO_MANAGEFILTERSContainer.setC2ShowFunction(function(UC) { UC.show(); });
   DDO_MANAGEFILTERSContainer.addEventHandler("OnOptionClicked", this.e110o2_client);
   this.setUserControl(DDO_MANAGEFILTERSContainer);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"LAYOUTMAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[6]={ id: 6, fld:"TABLEMAIN",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[8]={ id: 8, fld:"",grid:0};
   GXValidFnc[11]={ id: 11, fld:"TABLEHEADER",grid:0};
   GXValidFnc[12]={ id: 12, fld:"",grid:0};
   GXValidFnc[13]={ id: 13, fld:"TABLEACTIONS",grid:0};
   GXValidFnc[14]={ id: 14, fld:"",grid:0};
   GXValidFnc[15]={ id: 15, fld:"TEXTBLOCKTITLE", format:0,grid:0};
   GXValidFnc[16]={ id: 16, fld:"",grid:0};
   GXValidFnc[17]={ id: 17, fld:"",grid:0};
   GXValidFnc[18]={ id: 18, fld:"",grid:0};
   GXValidFnc[19]={ id: 19, fld:"BTNINSERT",grid:0,evt:"e150o2_client"};
   GXValidFnc[20]={ id: 20, fld:"",grid:0};
   GXValidFnc[21]={ id: 21, fld:"BTNEXPORT",grid:0,evt:"e160o2_client"};
   GXValidFnc[22]={ id: 22, fld:"",grid:0};
   GXValidFnc[23]={ id: 23, fld:"BTNEXPORTREPORT",grid:0,evt:"e170o2_client"};
   GXValidFnc[24]={ id: 24, fld:"",grid:0};
   GXValidFnc[25]={ id: 25, fld:"TABLERIGHTHEADER",grid:0};
   GXValidFnc[30]={ id: 30, fld:"TABLEFILTERS",grid:0};
   GXValidFnc[33]={ id: 33, fld:"",grid:0};
   GXValidFnc[34]={ id:34 ,lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[this.GridContainer],fld:"vFILTERFULLTEXT",gxz:"ZV91FilterFullText",gxold:"OV91FilterFullText",gxvar:"AV91FilterFullText",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV91FilterFullText=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV91FilterFullText=Value},v2c:function(){gx.fn.setControlValue("vFILTERFULLTEXT",gx.O.AV91FilterFullText,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.AV91FilterFullText=this.val()},val:function(){return gx.fn.getControlValue("vFILTERFULLTEXT")},nac:gx.falseFn};
   this.declareDomainHdlr( 34 , function() {
   });
   GXValidFnc[35]={ id: 35, fld:"",grid:0};
   GXValidFnc[36]={ id: 36, fld:"",grid:0};
   GXValidFnc[38]={ id: 38, fld:"",grid:0};
   GXValidFnc[39]={ id: 39, fld:"",grid:0};
   GXValidFnc[40]={ id: 40, fld:"GRIDTABLEWITHPAGINATIONBAR",grid:0};
   GXValidFnc[41]={ id: 41, fld:"",grid:0};
   GXValidFnc[42]={ id: 42, fld:"",grid:0};
   GXValidFnc[44]={ id:44 ,lvl:2,type:"char",len:20,dec:0,sign:false,ro:1,isacc:0,grid:43,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vUPDATE",gxz:"ZV13Update",gxold:"OV13Update",gxvar:"AV13Update",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.AV13Update=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV13Update=Value},v2c:function(row){gx.fn.setGridControlValue("vUPDATE",row || gx.fn.currentGridRowImpl(43),gx.O.AV13Update,1)},c2v:function(row){if(this.val(row)!==undefined)gx.O.AV13Update=this.val(row)},val:function(row){return gx.fn.getGridControlValue("vUPDATE",row || gx.fn.currentGridRowImpl(43))},nac:gx.falseFn};
   GXValidFnc[45]={ id:45 ,lvl:2,type:"char",len:20,dec:0,sign:false,ro:1,isacc:0,grid:43,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vDELETE",gxz:"ZV14Delete",gxold:"OV14Delete",gxvar:"AV14Delete",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.AV14Delete=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV14Delete=Value},v2c:function(row){gx.fn.setGridControlValue("vDELETE",row || gx.fn.currentGridRowImpl(43),gx.O.AV14Delete,1)},c2v:function(row){if(this.val(row)!==undefined)gx.O.AV14Delete=this.val(row)},val:function(row){return gx.fn.getGridControlValue("vDELETE",row || gx.fn.currentGridRowImpl(43))},nac:gx.falseFn};
   GXValidFnc[46]={ id:46 ,lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:43,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vUAASSOCIATEFUNCTIONALITIES",gxz:"ZV34UAAssociateFunctionalities",gxold:"OV34UAAssociateFunctionalities",gxvar:"AV34UAAssociateFunctionalities",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.AV34UAAssociateFunctionalities=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV34UAAssociateFunctionalities=Value},v2c:function(row){gx.fn.setGridMultimediaValue("vUAASSOCIATEFUNCTIONALITIES",row || gx.fn.currentGridRowImpl(43),gx.O.AV34UAAssociateFunctionalities,gx.O.AV102Uaassociatefunctionalities_GXI)},c2v:function(row){gx.O.AV102Uaassociatefunctionalities_GXI=this.val_GXI();if(this.val(row)!==undefined)gx.O.AV34UAAssociateFunctionalities=this.val(row)},val:function(row){return gx.fn.getGridControlValue("vUAASSOCIATEFUNCTIONALITIES",row || gx.fn.currentGridRowImpl(43))},val_GXI:function(row){return gx.fn.getGridControlValue("vUAASSOCIATEFUNCTIONALITIES_GXI",row || gx.fn.currentGridRowImpl(43))}, gxvar_GXI:'AV102Uaassociatefunctionalities_GXI',nac:gx.falseFn};
   GXValidFnc[47]={ id:47 ,lvl:2,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:1,isacc:0,grid:43,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SECROLEID",gxz:"Z10SecRoleId",gxold:"O10SecRoleId",gxvar:"A10SecRoleId",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.A10SecRoleId=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.Z10SecRoleId=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridControlValue("SECROLEID",row || gx.fn.currentGridRowImpl(43),gx.O.A10SecRoleId,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.A10SecRoleId=gx.num.intval(this.val(row))},val:function(row){return gx.fn.getGridIntegerValue("SECROLEID",row || gx.fn.currentGridRowImpl(43),'.')},nac:gx.falseFn};
   GXValidFnc[48]={ id:48 ,lvl:2,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:43,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SECROLENAME",gxz:"Z91SecRoleName",gxold:"O91SecRoleName",gxvar:"A91SecRoleName",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A91SecRoleName=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z91SecRoleName=Value},v2c:function(row){gx.fn.setGridControlValue("SECROLENAME",row || gx.fn.currentGridRowImpl(43),gx.O.A91SecRoleName,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.A91SecRoleName=this.val(row)},val:function(row){return gx.fn.getGridControlValue("SECROLENAME",row || gx.fn.currentGridRowImpl(43))},nac:gx.falseFn};
   GXValidFnc[49]={ id:49 ,lvl:2,type:"svchar",len:120,dec:0,sign:false,ro:1,isacc:0,grid:43,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"SECROLEDESCRIPTION",gxz:"Z90SecRoleDescription",gxold:"O90SecRoleDescription",gxvar:"A90SecRoleDescription",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.A90SecRoleDescription=Value},v2z:function(Value){if(Value!==undefined)gx.O.Z90SecRoleDescription=Value},v2c:function(row){gx.fn.setGridControlValue("SECROLEDESCRIPTION",row || gx.fn.currentGridRowImpl(43),gx.O.A90SecRoleDescription,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.A90SecRoleDescription=this.val(row)},val:function(row){return gx.fn.getGridControlValue("SECROLEDESCRIPTION",row || gx.fn.currentGridRowImpl(43))},nac:gx.falseFn};
   GXValidFnc[50]={ id: 50, fld:"",grid:0};
   GXValidFnc[51]={ id: 51, fld:"",grid:0};
   GXValidFnc[53]={ id: 53, fld:"",grid:0};
   GXValidFnc[54]={ id: 54, fld:"",grid:0};
   GXValidFnc[55]={ id: 55, fld:"HTML_BOTTOMAUXILIARCONTROLS",grid:0};
   this.AV91FilterFullText = "" ;
   this.ZV91FilterFullText = "" ;
   this.OV91FilterFullText = "" ;
   this.ZV13Update = "" ;
   this.OV13Update = "" ;
   this.ZV14Delete = "" ;
   this.OV14Delete = "" ;
   this.ZV34UAAssociateFunctionalities = "" ;
   this.OV34UAAssociateFunctionalities = "" ;
   this.Z10SecRoleId = 0 ;
   this.O10SecRoleId = 0 ;
   this.Z91SecRoleName = "" ;
   this.O91SecRoleName = "" ;
   this.Z90SecRoleDescription = "" ;
   this.O90SecRoleDescription = "" ;
   this.AV68ManageFiltersData = [ ] ;
   this.AV91FilterFullText = "" ;
   this.AV89GridCurrentPage = 0 ;
   this.AV78DDO_TitleSettingsIcons = {Default:"",Default_GXI:"",Filtered:"",Filtered_GXI:"",SortedASC:"",SortedASC_GXI:"",SortedDSC:"",SortedDSC_GXI:"",FilteredSortedASC:"",FilteredSortedASC_GXI:"",FilteredSortedDSC:"",FilteredSortedDSC_GXI:"",OptionSortASC:"",OptionSortASC_GXI:"",OptionSortDSC:"",OptionSortDSC_GXI:"",OptionApplyFilter:"",OptionApplyFilter_GXI:"",OptionFilteringData:"",OptionFilteringData_GXI:"",OptionCleanFilters:"",OptionCleanFilters_GXI:"",SelectedOption:"",SelectedOption_GXI:"",MultiselOption:"",MultiselOption_GXI:"",MultiselSelOption:"",MultiselSelOption_GXI:"",TreeviewCollapse:"",TreeviewCollapse_GXI:"",TreeviewExpand:"",TreeviewExpand_GXI:""} ;
   this.AV13Update = "" ;
   this.AV14Delete = "" ;
   this.AV34UAAssociateFunctionalities = "" ;
   this.A10SecRoleId = 0 ;
   this.A91SecRoleName = "" ;
   this.A90SecRoleDescription = "" ;
   this.AV64ManageFiltersExecutionStep = 0 ;
   this.AV71TFSecRoleName = "" ;
   this.AV72TFSecRoleName_Sel = "" ;
   this.AV75TFSecRoleDescription = "" ;
   this.AV76TFSecRoleDescription_Sel = "" ;
   this.AV96Pgmname = "" ;
   this.AV44OrderedBy = 0 ;
   this.AV45OrderedDsc = false ;
   this.AV41GridState = {CurrentPage:0,OrderedBy:0,OrderedDsc:false,HidingSearch:0,PageSize:"",CollapsedRecords:"",GroupBy:"",FilterValues:[],DynamicFilters:[]} ;
   this.Events = {"e120o2_client": ["GRIDPAGINATIONBAR.CHANGEPAGE", true] ,"e130o2_client": ["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE", true] ,"e140o2_client": ["DDO_GRID.ONOPTIONCLICKED", true] ,"e110o2_client": ["DDO_MANAGEFILTERS.ONOPTIONCLICKED", true] ,"e150o2_client": ["'DOINSERT'", true] ,"e160o2_client": ["'DOEXPORT'", true] ,"e170o2_client": ["'DOEXPORTREPORT'", true] ,"e210o2_client": ["ENTER", true] ,"e220o2_client": ["CANCEL", true]};
   this.EvtParms["REFRESH"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{av:'gx.fn.getCtrlProperty("vUAASSOCIATEFUNCTIONALITIES","Title")',ctrl:'vUAASSOCIATEFUNCTIONALITIES',prop:'Title'},{av:'AV64ManageFiltersExecutionStep',fld:'vMANAGEFILTERSEXECUTIONSTEP',pic:'9'},{ctrl:'GRID',prop:'Rows'},{av:'AV91FilterFullText',fld:'vFILTERFULLTEXT',pic:''},{av:'AV71TFSecRoleName',fld:'vTFSECROLENAME',pic:''},{av:'AV72TFSecRoleName_Sel',fld:'vTFSECROLENAME_SEL',pic:''},{av:'AV75TFSecRoleDescription',fld:'vTFSECROLEDESCRIPTION',pic:''},{av:'AV76TFSecRoleDescription_Sel',fld:'vTFSECROLEDESCRIPTION_SEL',pic:''},{av:'AV96Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'AV44OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV45OrderedDsc',fld:'vORDEREDDSC',pic:''}],[{av:'AV64ManageFiltersExecutionStep',fld:'vMANAGEFILTERSEXECUTIONSTEP',pic:'9'},{av:'AV89GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV90GridPageCount',fld:'vGRIDPAGECOUNT',pic:'ZZZZZZZZZ9'},{av:'AV68ManageFiltersData',fld:'vMANAGEFILTERSDATA',pic:''},{av:'AV41GridState',fld:'vGRIDSTATE',pic:''}]];
   this.EvtParms["START"] = [[{av:'AV96Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'AV44OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV45OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV41GridState',fld:'vGRIDSTATE',pic:''},{av:'AV72TFSecRoleName_Sel',fld:'vTFSECROLENAME_SEL',pic:''},{av:'AV76TFSecRoleDescription_Sel',fld:'vTFSECROLEDESCRIPTION_SEL',pic:''},{av:'AV71TFSecRoleName',fld:'vTFSECROLENAME',pic:''},{av:'AV75TFSecRoleDescription',fld:'vTFSECROLEDESCRIPTION',pic:''}],[{ctrl:'GRID',prop:'Rows'},{av:'this.DDO_GRIDContainer.GridInternalName',ctrl:'DDO_GRID',prop:'GridInternalName'},{ctrl:'FORM',prop:'Caption'},{av:'AV44OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV78DDO_TitleSettingsIcons',fld:'vDDO_TITLESETTINGSICONS',pic:''},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'},{av:'gx.fn.getCtrlProperty("TEXTBLOCKTITLE","Caption")',ctrl:'TEXTBLOCKTITLE',prop:'Caption'},{av:'gx.fn.getCtrlProperty("vUAASSOCIATEFUNCTIONALITIES","Title")',ctrl:'vUAASSOCIATEFUNCTIONALITIES',prop:'Title'},{av:'AV68ManageFiltersData',fld:'vMANAGEFILTERSDATA',pic:''},{av:'AV41GridState',fld:'vGRIDSTATE',pic:''},{av:'AV45OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{av:'AV91FilterFullText',fld:'vFILTERFULLTEXT',pic:''},{av:'AV64ManageFiltersExecutionStep',fld:'vMANAGEFILTERSEXECUTIONSTEP',pic:'9'},{av:'AV71TFSecRoleName',fld:'vTFSECROLENAME',pic:''},{av:'AV72TFSecRoleName_Sel',fld:'vTFSECROLENAME_SEL',pic:''},{av:'AV75TFSecRoleDescription',fld:'vTFSECROLEDESCRIPTION',pic:''},{av:'AV76TFSecRoleDescription_Sel',fld:'vTFSECROLEDESCRIPTION_SEL',pic:''},{av:'AV96Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'this.DDO_GRIDContainer.SortedStatus',ctrl:'DDO_GRID',prop:'SortedStatus'},{av:'this.DDO_GRIDContainer.SelectedValue_set',ctrl:'DDO_GRID',prop:'SelectedValue_set'},{av:'this.DDO_GRIDContainer.FilteredText_set',ctrl:'DDO_GRID',prop:'FilteredText_set'}]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV91FilterFullText',fld:'vFILTERFULLTEXT',pic:''},{av:'AV64ManageFiltersExecutionStep',fld:'vMANAGEFILTERSEXECUTIONSTEP',pic:'9'},{av:'AV71TFSecRoleName',fld:'vTFSECROLENAME',pic:''},{av:'AV72TFSecRoleName_Sel',fld:'vTFSECROLENAME_SEL',pic:''},{av:'AV75TFSecRoleDescription',fld:'vTFSECROLEDESCRIPTION',pic:''},{av:'AV76TFSecRoleDescription_Sel',fld:'vTFSECROLEDESCRIPTION_SEL',pic:''},{av:'AV96Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'AV44OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV45OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'gx.fn.getCtrlProperty("vUAASSOCIATEFUNCTIONALITIES","Title")',ctrl:'vUAASSOCIATEFUNCTIONALITIES',prop:'Title'},{av:'this.GRIDPAGINATIONBARContainer.SelectedPage',ctrl:'GRIDPAGINATIONBAR',prop:'SelectedPage'}],[]];
   this.EvtParms["GRIDPAGINATIONBAR.CHANGEROWSPERPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV91FilterFullText',fld:'vFILTERFULLTEXT',pic:''},{av:'AV64ManageFiltersExecutionStep',fld:'vMANAGEFILTERSEXECUTIONSTEP',pic:'9'},{av:'AV71TFSecRoleName',fld:'vTFSECROLENAME',pic:''},{av:'AV72TFSecRoleName_Sel',fld:'vTFSECROLENAME_SEL',pic:''},{av:'AV75TFSecRoleDescription',fld:'vTFSECROLEDESCRIPTION',pic:''},{av:'AV76TFSecRoleDescription_Sel',fld:'vTFSECROLEDESCRIPTION_SEL',pic:''},{av:'AV96Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'AV44OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV45OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'gx.fn.getCtrlProperty("vUAASSOCIATEFUNCTIONALITIES","Title")',ctrl:'vUAASSOCIATEFUNCTIONALITIES',prop:'Title'},{av:'this.GRIDPAGINATIONBARContainer.RowsPerPageSelectedValue',ctrl:'GRIDPAGINATIONBAR',prop:'RowsPerPageSelectedValue'}],[{ctrl:'GRID',prop:'Rows'}]];
   this.EvtParms["DDO_GRID.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV91FilterFullText',fld:'vFILTERFULLTEXT',pic:''},{av:'AV64ManageFiltersExecutionStep',fld:'vMANAGEFILTERSEXECUTIONSTEP',pic:'9'},{av:'AV71TFSecRoleName',fld:'vTFSECROLENAME',pic:''},{av:'AV72TFSecRoleName_Sel',fld:'vTFSECROLENAME_SEL',pic:''},{av:'AV75TFSecRoleDescription',fld:'vTFSECROLEDESCRIPTION',pic:''},{av:'AV76TFSecRoleDescription_Sel',fld:'vTFSECROLEDESCRIPTION_SEL',pic:''},{av:'AV96Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'AV44OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV45OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'gx.fn.getCtrlProperty("vUAASSOCIATEFUNCTIONALITIES","Title")',ctrl:'vUAASSOCIATEFUNCTIONALITIES',prop:'Title'},{av:'this.DDO_GRIDContainer.ActiveEventKey',ctrl:'DDO_GRID',prop:'ActiveEventKey'},{av:'this.DDO_GRIDContainer.SelectedValue_get',ctrl:'DDO_GRID',prop:'SelectedValue_get'},{av:'this.DDO_GRIDContainer.SelectedColumn',ctrl:'DDO_GRID',prop:'SelectedColumn'},{av:'this.DDO_GRIDContainer.FilteredText_get',ctrl:'DDO_GRID',prop:'FilteredText_get'}],[{av:'AV44OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV45OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV71TFSecRoleName',fld:'vTFSECROLENAME',pic:''},{av:'AV72TFSecRoleName_Sel',fld:'vTFSECROLENAME_SEL',pic:''},{av:'AV75TFSecRoleDescription',fld:'vTFSECROLEDESCRIPTION',pic:''},{av:'AV76TFSecRoleDescription_Sel',fld:'vTFSECROLEDESCRIPTION_SEL',pic:''},{av:'this.DDO_GRIDContainer.SortedStatus',ctrl:'DDO_GRID',prop:'SortedStatus'}]];
   this.EvtParms["GRID.LOAD"] = [[{av:'A10SecRoleId',fld:'SECROLEID',pic:'ZZZ9',hsh:true}],[{av:'AV13Update',fld:'vUPDATE',pic:''},{av:'gx.fn.getCtrlProperty("vUPDATE","Link")',ctrl:'vUPDATE',prop:'Link'},{av:'AV14Delete',fld:'vDELETE',pic:''},{av:'gx.fn.getCtrlProperty("vDELETE","Link")',ctrl:'vDELETE',prop:'Link'},{av:'AV34UAAssociateFunctionalities',fld:'vUAASSOCIATEFUNCTIONALITIES',pic:''},{av:'gx.fn.getCtrlProperty("vUAASSOCIATEFUNCTIONALITIES","Tooltiptext")',ctrl:'vUAASSOCIATEFUNCTIONALITIES',prop:'Tooltiptext'},{av:'gx.fn.getCtrlProperty("vUAASSOCIATEFUNCTIONALITIES","Link")',ctrl:'vUAASSOCIATEFUNCTIONALITIES',prop:'Link'},{av:'gx.fn.getCtrlProperty("SECROLENAME","Link")',ctrl:'SECROLENAME',prop:'Link'}]];
   this.EvtParms["DDO_MANAGEFILTERS.ONOPTIONCLICKED"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV91FilterFullText',fld:'vFILTERFULLTEXT',pic:''},{av:'AV64ManageFiltersExecutionStep',fld:'vMANAGEFILTERSEXECUTIONSTEP',pic:'9'},{av:'AV71TFSecRoleName',fld:'vTFSECROLENAME',pic:''},{av:'AV72TFSecRoleName_Sel',fld:'vTFSECROLENAME_SEL',pic:''},{av:'AV75TFSecRoleDescription',fld:'vTFSECROLEDESCRIPTION',pic:''},{av:'AV76TFSecRoleDescription_Sel',fld:'vTFSECROLEDESCRIPTION_SEL',pic:''},{av:'AV96Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'AV44OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV45OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'gx.fn.getCtrlProperty("vUAASSOCIATEFUNCTIONALITIES","Title")',ctrl:'vUAASSOCIATEFUNCTIONALITIES',prop:'Title'},{av:'this.DDO_MANAGEFILTERSContainer.ActiveEventKey',ctrl:'DDO_MANAGEFILTERS',prop:'ActiveEventKey'},{av:'AV41GridState',fld:'vGRIDSTATE',pic:''}],[{av:'AV64ManageFiltersExecutionStep',fld:'vMANAGEFILTERSEXECUTIONSTEP',pic:'9'},{av:'AV41GridState',fld:'vGRIDSTATE',pic:''},{av:'AV44OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV45OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV91FilterFullText',fld:'vFILTERFULLTEXT',pic:''},{av:'AV71TFSecRoleName',fld:'vTFSECROLENAME',pic:''},{av:'AV72TFSecRoleName_Sel',fld:'vTFSECROLENAME_SEL',pic:''},{av:'AV75TFSecRoleDescription',fld:'vTFSECROLEDESCRIPTION',pic:''},{av:'AV76TFSecRoleDescription_Sel',fld:'vTFSECROLEDESCRIPTION_SEL',pic:''},{av:'this.DDO_GRIDContainer.SelectedValue_set',ctrl:'DDO_GRID',prop:'SelectedValue_set'},{av:'this.DDO_GRIDContainer.FilteredText_set',ctrl:'DDO_GRID',prop:'FilteredText_set'},{av:'this.DDO_GRIDContainer.SortedStatus',ctrl:'DDO_GRID',prop:'SortedStatus'},{av:'AV89GridCurrentPage',fld:'vGRIDCURRENTPAGE',pic:'ZZZZZZZZZ9'},{av:'AV90GridPageCount',fld:'vGRIDPAGECOUNT',pic:'ZZZZZZZZZ9'},{av:'AV68ManageFiltersData',fld:'vMANAGEFILTERSDATA',pic:''}]];
   this.EvtParms["'DOINSERT'"] = [[{av:'A10SecRoleId',fld:'SECROLEID',pic:'ZZZ9',hsh:true}],[]];
   this.EvtParms["'DOEXPORT'"] = [[{av:'AV96Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'AV44OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV45OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV41GridState',fld:'vGRIDSTATE',pic:''},{av:'AV72TFSecRoleName_Sel',fld:'vTFSECROLENAME_SEL',pic:''},{av:'AV76TFSecRoleDescription_Sel',fld:'vTFSECROLEDESCRIPTION_SEL',pic:''},{av:'AV71TFSecRoleName',fld:'vTFSECROLENAME',pic:''},{av:'AV75TFSecRoleDescription',fld:'vTFSECROLEDESCRIPTION',pic:''}],[{av:'AV41GridState',fld:'vGRIDSTATE',pic:''},{av:'AV44OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV45OrderedDsc',fld:'vORDEREDDSC',pic:''},{ctrl:'GRID',prop:'Rows'},{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{av:'AV91FilterFullText',fld:'vFILTERFULLTEXT',pic:''},{av:'AV64ManageFiltersExecutionStep',fld:'vMANAGEFILTERSEXECUTIONSTEP',pic:'9'},{av:'AV71TFSecRoleName',fld:'vTFSECROLENAME',pic:''},{av:'AV72TFSecRoleName_Sel',fld:'vTFSECROLENAME_SEL',pic:''},{av:'AV75TFSecRoleDescription',fld:'vTFSECROLEDESCRIPTION',pic:''},{av:'AV76TFSecRoleDescription_Sel',fld:'vTFSECROLEDESCRIPTION_SEL',pic:''},{av:'AV96Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'gx.fn.getCtrlProperty("vUAASSOCIATEFUNCTIONALITIES","Title")',ctrl:'vUAASSOCIATEFUNCTIONALITIES',prop:'Title'},{av:'this.DDO_GRIDContainer.SortedStatus',ctrl:'DDO_GRID',prop:'SortedStatus'},{av:'this.DDO_GRIDContainer.SelectedValue_set',ctrl:'DDO_GRID',prop:'SelectedValue_set'},{av:'this.DDO_GRIDContainer.FilteredText_set',ctrl:'DDO_GRID',prop:'FilteredText_set'}]];
   this.EvtParms["'DOEXPORTREPORT'"] = [[{av:'AV96Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'AV44OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV45OrderedDsc',fld:'vORDEREDDSC',pic:''},{av:'AV41GridState',fld:'vGRIDSTATE',pic:''},{av:'AV72TFSecRoleName_Sel',fld:'vTFSECROLENAME_SEL',pic:''},{av:'AV76TFSecRoleDescription_Sel',fld:'vTFSECROLEDESCRIPTION_SEL',pic:''},{av:'AV71TFSecRoleName',fld:'vTFSECROLENAME',pic:''},{av:'AV75TFSecRoleDescription',fld:'vTFSECROLEDESCRIPTION',pic:''}],[{av:'this.INNEWWINDOW1Container.Target',ctrl:'INNEWWINDOW1',prop:'Target'},{av:'this.INNEWWINDOW1Container.Height',ctrl:'INNEWWINDOW1',prop:'Height'},{av:'this.INNEWWINDOW1Container.Width',ctrl:'INNEWWINDOW1',prop:'Width'},{av:'AV41GridState',fld:'vGRIDSTATE',pic:''},{av:'AV44OrderedBy',fld:'vORDEREDBY',pic:'ZZZ9'},{av:'AV45OrderedDsc',fld:'vORDEREDDSC',pic:''},{ctrl:'GRID',prop:'Rows'},{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{av:'AV91FilterFullText',fld:'vFILTERFULLTEXT',pic:''},{av:'AV64ManageFiltersExecutionStep',fld:'vMANAGEFILTERSEXECUTIONSTEP',pic:'9'},{av:'AV71TFSecRoleName',fld:'vTFSECROLENAME',pic:''},{av:'AV72TFSecRoleName_Sel',fld:'vTFSECROLENAME_SEL',pic:''},{av:'AV75TFSecRoleDescription',fld:'vTFSECROLEDESCRIPTION',pic:''},{av:'AV76TFSecRoleDescription_Sel',fld:'vTFSECROLEDESCRIPTION_SEL',pic:''},{av:'AV96Pgmname',fld:'vPGMNAME',pic:'',hsh:true},{av:'gx.fn.getCtrlProperty("vUAASSOCIATEFUNCTIONALITIES","Title")',ctrl:'vUAASSOCIATEFUNCTIONALITIES',prop:'Title'},{av:'this.DDO_GRIDContainer.SortedStatus',ctrl:'DDO_GRID',prop:'SortedStatus'},{av:'this.DDO_GRIDContainer.SelectedValue_set',ctrl:'DDO_GRID',prop:'SelectedValue_set'},{av:'this.DDO_GRIDContainer.FilteredText_set',ctrl:'DDO_GRID',prop:'FilteredText_set'}]];
   this.setVCMap("AV64ManageFiltersExecutionStep", "vMANAGEFILTERSEXECUTIONSTEP", 0, "int", 1, 0);
   this.setVCMap("AV71TFSecRoleName", "vTFSECROLENAME", 0, "svchar", 40, 0);
   this.setVCMap("AV72TFSecRoleName_Sel", "vTFSECROLENAME_SEL", 0, "svchar", 40, 0);
   this.setVCMap("AV75TFSecRoleDescription", "vTFSECROLEDESCRIPTION", 0, "svchar", 120, 0);
   this.setVCMap("AV76TFSecRoleDescription_Sel", "vTFSECROLEDESCRIPTION_SEL", 0, "svchar", 120, 0);
   this.setVCMap("AV96Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("AV44OrderedBy", "vORDEREDBY", 0, "int", 4, 0);
   this.setVCMap("AV45OrderedDsc", "vORDEREDDSC", 0, "boolean", 4, 0);
   this.setVCMap("AV41GridState", "vGRIDSTATE", 0, "WWPBaseObjects\WWPGridState", 0, 0);
   this.setVCMap("AV64ManageFiltersExecutionStep", "vMANAGEFILTERSEXECUTIONSTEP", 0, "int", 1, 0);
   this.setVCMap("AV71TFSecRoleName", "vTFSECROLENAME", 0, "svchar", 40, 0);
   this.setVCMap("AV72TFSecRoleName_Sel", "vTFSECROLENAME_SEL", 0, "svchar", 40, 0);
   this.setVCMap("AV75TFSecRoleDescription", "vTFSECROLEDESCRIPTION", 0, "svchar", 120, 0);
   this.setVCMap("AV76TFSecRoleDescription_Sel", "vTFSECROLEDESCRIPTION_SEL", 0, "svchar", 120, 0);
   this.setVCMap("AV96Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("AV44OrderedBy", "vORDEREDBY", 0, "int", 4, 0);
   this.setVCMap("AV45OrderedDsc", "vORDEREDDSC", 0, "boolean", 4, 0);
   this.setVCMap("AV64ManageFiltersExecutionStep", "vMANAGEFILTERSEXECUTIONSTEP", 0, "int", 1, 0);
   this.setVCMap("AV71TFSecRoleName", "vTFSECROLENAME", 0, "svchar", 40, 0);
   this.setVCMap("AV72TFSecRoleName_Sel", "vTFSECROLENAME_SEL", 0, "svchar", 40, 0);
   this.setVCMap("AV75TFSecRoleDescription", "vTFSECROLEDESCRIPTION", 0, "svchar", 120, 0);
   this.setVCMap("AV76TFSecRoleDescription_Sel", "vTFSECROLEDESCRIPTION_SEL", 0, "svchar", 120, 0);
   this.setVCMap("AV96Pgmname", "vPGMNAME", 0, "char", 129, 0);
   this.setVCMap("AV44OrderedBy", "vORDEREDBY", 0, "int", 4, 0);
   this.setVCMap("AV45OrderedDsc", "vORDEREDDSC", 0, "boolean", 4, 0);
   GridContainer.addRefreshingVar(this.GXValidFnc[34]);
   GridContainer.addRefreshingVar({rfrVar:"AV64ManageFiltersExecutionStep"});
   GridContainer.addRefreshingVar({rfrVar:"AV71TFSecRoleName"});
   GridContainer.addRefreshingVar({rfrVar:"AV72TFSecRoleName_Sel"});
   GridContainer.addRefreshingVar({rfrVar:"AV75TFSecRoleDescription"});
   GridContainer.addRefreshingVar({rfrVar:"AV76TFSecRoleDescription_Sel"});
   GridContainer.addRefreshingVar({rfrVar:"AV96Pgmname"});
   GridContainer.addRefreshingVar({rfrVar:"AV44OrderedBy"});
   GridContainer.addRefreshingVar({rfrVar:"AV45OrderedDsc"});
   GridContainer.addRefreshingVar({rfrVar:"AV34UAAssociateFunctionalities", rfrProp:"Title", gxAttId:"Uaassociatefunctionalities"});
   GridContainer.addRefreshingParm(this.GXValidFnc[34]);
   GridContainer.addRefreshingParm({rfrVar:"AV64ManageFiltersExecutionStep"});
   GridContainer.addRefreshingParm({rfrVar:"AV71TFSecRoleName"});
   GridContainer.addRefreshingParm({rfrVar:"AV72TFSecRoleName_Sel"});
   GridContainer.addRefreshingParm({rfrVar:"AV75TFSecRoleDescription"});
   GridContainer.addRefreshingParm({rfrVar:"AV76TFSecRoleDescription_Sel"});
   GridContainer.addRefreshingParm({rfrVar:"AV96Pgmname"});
   GridContainer.addRefreshingParm({rfrVar:"AV44OrderedBy"});
   GridContainer.addRefreshingParm({rfrVar:"AV45OrderedDsc"});
   GridContainer.addRefreshingParm({rfrVar:"AV34UAAssociateFunctionalities", rfrProp:"Title", gxAttId:"Uaassociatefunctionalities"});
   this.Initialize( );
});
gx.wi( function() { gx.createParentObj(wwpbaseobjects.secroleww);});
